[package]
name = "image-optimizer"
version = "0.3.1"
authors = ["Daniel Naschberger <daniel@naschi.at>"]
edition = "2021"
description = "A tool to optimize images for web."
readme = "README.md"
repository = "https://github.com/naschidaniel/image-optimizer/"
license = "GPL-3.0"


[dependencies]
chrono = "0.4.19"
clap = "3.0.0-beta.5"
image = "0.23.14"
glob = "0.3.0"
tempfile = "3.2.0"
webp = "0.2"
