name: release

on:
  push:
    branches:
      - main

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Rust check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Rust build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/image-optimizer
          asset_name: image-optimizer-linux-amd64
          overwrite: true
  
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Rust build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/image-optimizer
          asset_name: image-optimizer-win
          overwrite: true