name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Build for Linux
        run: cargo build --target x86_64-unknown-linux-musl --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/image-optimizer
          asset_name: image-optimizer-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
