
on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          default: true
          override: true
      - name: Create Release
        if: matrix.platform == 'ubuntu-latest'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Rust check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo test
        if: matrix.platform != 'macos-latest'
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test
      - name: Rust build for Linux
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Release Linux Asset
        if: matrix.platform == 'linux-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/image-optimizer
          asset_name: image-optimizer-linux
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Release MacOs Asset
        if: matrix.platform == 'macos-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/image-optimizer
          asset_name: image-optimizer-macos
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Release Windows Asset
        if: matrix.platform == 'windows-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/image-optimizer
          asset_name: image-optimizer.exe
          tag: ${{ github.ref }}
          overwrite: true
